name: Trigger Target Workflow

on: 
  push:
    branches:
      - main

jobs:
  trigger: 
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in umbrella repo
        run: |
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/staillansag/msr-vm-devops/dispatches \
            -d "{\"event_type\": \"package-change\"}"